title: bradyap.dev
repository: bradyap/bradyap.github.io
#email: me@bradyap.dev
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#linkedin_username: bradypettengill
#github_username:  bradyap

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

# Exclude from processing.
exclude:
  - Gemfile
  - .gitignore
  - .git

author:
  name: "Brady Pettengill"
  #avatar: "path to image here"
  bio: "Undergraduate Data Science Student at George Mason University"
  location: "Reston, Virginia"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/bradyap"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/bradypettengill/"
    #- label: "me@bradyap.dev"
    #  icon: "fas fa-envelope"
    #  url: "mailto:me@bradyap.dev"
    #- label: "Resume (PDF)"
    # icon: "fas fa-file-pdf"
    #  url: "path to resume here"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      sidebar: nav

header_pages:
  - index.md
  - pages/projects.md